name: Deploy Staging (Vercel)

on:
  workflow_dispatch: {}
  push:
    branches: [ "staging" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Validate hook URL
        run: |
          if [ -z "${{ secrets.VERCEL_DEPLOY_HOOK_URL_STAGING }}" ]; then
            echo "Missing secret VERCEL_DEPLOY_HOOK_URL_STAGING"; exit 2;
          fi
      - name: Trigger Vercel deploy (staging)
        run: |
          curl -fsS -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL_STAGING }}" || { echo "Vercel hook failed"; exit 3; }