name: Deploy Staging (Vercel)

on:
  workflow_dispatch: {}
  push:
    branches: ["staging"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel deploy (staging)
        env:
          HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK_URL_STAGING }}
        run: |
          if [ -z "$HOOK" ]; then echo "Missing VERCEL_DEPLOY_HOOK_URL_STAGING"; exit 2; fi
          curl -fsS -X POST "$HOOK"