name: Deploy Staging (Vercel)

on:
  # push:
  #   branches: [staging]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Validate required secret
        run: |
          test -n "${{ secrets.VERCEL_DEPLOY_HOOK_URL_STAGING }}" || { 
            echo "Missing secret: VERCEL_DEPLOY_HOOK_URL_STAGING"; exit 1; 
          }

      - name: Trigger Vercel Deploy (staging)
        run: |
          curl -fsS -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL_STAGING }}"