name: Trigger Vercel Deploy
on:
  workflow_dispatch:
  push:
    branches: [ main ]    # se vuoi anche staging, aggiungi 'staging'
jobs:
  call-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Validate secret is present
        run: |
          test -n "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}" || { echo "Missing secret VERCEL_DEPLOY_HOOK_URL"; exit 2; }
      - name: Trigger Vercel Hook
        env:
          HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          STATUS=$(curl -s -o resp.json -w "%{http_code}" -X POST "$HOOK")
          echo "HTTP Status: $STATUS"
          echo "Response:"
          cat resp.json
          test "$STATUS" = "200" -o "$STATUS" = "201" || { echo "Hook call failed with status $STATUS"; exit 3; }