name: Trigger Vercel Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  call-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Validate hook URL is present
        env:
          HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$HOOK" ]; then
            echo "Missing secret VERCEL_DEPLOY_HOOK_URL"
            exit 2
          fi
          echo "Secret looks set (length > 0)."

      - name: Trigger Vercel Hook (with logs)
        env:
          HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          echo "Hitting: ${HOOK%%\?*}?...(masked)"
          STATUS=$(curl -s -o resp.json -w "%{http_code}" -X POST "$HOOK")
          echo "HTTP Status: $STATUS"
          echo "Response body:"
          cat resp.json
          test "$STATUS" = "200" || { echo "Hook call failed"; exit 3; }