name: Update Datasets from Brevo API

on:
  schedule:
    # Run every night at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  update-datasets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true
        
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm init -y
        npm install axios
        
    - name: Run update script
      env:
        BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
      run: |
        node scripts/updateBrevoWithHistory.js
        
    - name: Commit and push changes
      run: |
        git add datasets.json historical-data.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update datasets and historical data from Brevo API [skip ci]"
          git push origin HEAD:main
        fi
