name: Update Datasets from Brevo API

on:
  schedule:
    # Run every night at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-datasets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
        
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm init -y
        npm install axios
        
    - name: Run update script
      env:
        BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
      run: |
        node scripts/updateBrevo.js
        
    - name: Commit and push changes
      env:
        ACTIONS_REPO_PAT: ${{ secrets.ACTIONS_REPO_PAT }}
        ACTIONS_REPO_USERNAME: ${{ secrets.ACTIONS_REPO_USERNAME }}
      run: |
        git add datasets.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update datasets from Brevo API [skip ci]"
          if [ -z "$ACTIONS_REPO_USERNAME" ]; then
            echo "ACTIONS_REPO_USERNAME secret not set. Please set it to the username that owns the PAT." && exit 1
          fi
          git remote set-url origin https://${ACTIONS_REPO_USERNAME}:${ACTIONS_REPO_PAT}@github.com/${GITHUB_REPOSITORY}.git
          git push origin HEAD:main
        fi
