name: Trigger Vercel via API

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Validate secrets
        run: |
          for v in VERCEL_TOKEN VERCEL_PROJECT_ID; do
            test -n "${{ secrets[$v] }}" || { echo "Missing secret $v"; exit 2; }
          done
      - name: Trigger deploy
        run: |
          BODY='{"projectId":"'"${{ secrets.VERCEL_PROJECT_ID }}"'","target":"production","gitSource":{"type":"github","ref":"main"}}'
          STATUS=$(curl -s -o resp.json -w "%{http_code}" -X POST "https://api.vercel.com/v13/deployments" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$BODY")
          echo "HTTP Status: $STATUS"
          cat resp.json
          test "$STATUS" = "200" -o "$STATUS" = "201" || { echo "Vercel API deploy failed"; exit 3; }
